# Generated by Django 4.1.7 on 2024-04-30 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('tg_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='telegram id агента')),
                ('fullName', models.CharField(max_length=256, verbose_name='ФИО агента')),
                ('date_of_birth', models.DateField(verbose_name='Тата рождения')),
                ('phone', models.CharField(max_length=256, verbose_name='Номер телефона')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='telegram username')),
                ('city', models.CharField(max_length=256, verbose_name='Город')),
                ('transport', models.CharField(max_length=256, verbose_name='Адрес доставки (ТК)')),
                ('qr_code', models.FileField(blank=True, null=True, upload_to='qr_code', verbose_name='Qr code агента')),
                ('code', models.CharField(max_length=256, unique=True, verbose_name='Код агента')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=256, verbose_name='ФИО клиента')),
                ('phone', models.CharField(max_length=256, verbose_name='Телефон клиента')),
                ('code', models.CharField(max_length=256, unique=True, verbose_name='Код клиента')),
                ('city', models.CharField(max_length=256, verbose_name='Город клиента')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agent', verbose_name='Агент клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='track')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Контроль таблица',
                'verbose_name_plural': 'Контроль таблицы',
            },
        ),
        migrations.CreateModel(
            name='Ransom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ransom')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Выкуп таблица',
                'verbose_name_plural': 'Выкуп таблицы',
            },
        ),
    ]
