# Generated by Django 4.1.7 on 2024-04-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ransom',
            name='client',
        ),
        migrations.RemoveField(
            model_name='track',
            name='client',
        ),
        migrations.AlterField(
            model_name='agent',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
